// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.xyz.protobuf;

public final class PersonOuterClass {
	private PersonOuterClass() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface PersonOrBuilder extends
			// @@protoc_insertion_point(interface_extends:com.xyz.protobuf.Person)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>required string id = 1;</code>
		 */
		boolean hasId();

		/**
		 * <code>required string id = 1;</code>
		 */
		java.lang.String getId();

		/**
		 * <code>required string id = 1;</code>
		 */
		com.google.protobuf.ByteString getIdBytes();
	}

	/**
	 * Protobuf type {@code com.xyz.protobuf.Person}
	 */
	public static final class Person extends com.google.protobuf.GeneratedMessage implements
			// @@protoc_insertion_point(message_implements:com.xyz.protobuf.Person)
			PersonOrBuilder {
		// Use Person.newBuilder() to construct.
		private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private Person(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final Person defaultInstance;

		public static Person getDefaultInstance() {
			return defaultInstance;
		}

		public Person getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Person(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						com.google.protobuf.ByteString bs = input.readBytes();
						bitField0_ |= 0x00000001;
						id_ = bs;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.xyz.protobuf.PersonOuterClass.internal_static_com_xyz_protobuf_Person_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.xyz.protobuf.PersonOuterClass.internal_static_com_xyz_protobuf_Person_fieldAccessorTable
					.ensureFieldAccessorsInitialized(com.xyz.protobuf.PersonOuterClass.Person.class,
							com.xyz.protobuf.PersonOuterClass.Person.Builder.class);
		}

		public static com.google.protobuf.Parser<Person> PARSER = new com.google.protobuf.AbstractParser<Person>() {
			public Person parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return new Person(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<Person> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		public static final int ID_FIELD_NUMBER = 1;
		private java.lang.Object id_;

		/**
		 * <code>required string id = 1;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string id = 1;</code>
		 */
		public java.lang.String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					id_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string id = 1;</code>
		 */
		public com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			id_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIdBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getIdBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.xyz.protobuf.PersonOuterClass.Person parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.xyz.protobuf.PersonOuterClass.Person prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.xyz.protobuf.Person}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:com.xyz.protobuf.Person)
				com.xyz.protobuf.PersonOuterClass.PersonOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.xyz.protobuf.PersonOuterClass.internal_static_com_xyz_protobuf_Person_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.xyz.protobuf.PersonOuterClass.internal_static_com_xyz_protobuf_Person_fieldAccessorTable
						.ensureFieldAccessorsInitialized(com.xyz.protobuf.PersonOuterClass.Person.class,
								com.xyz.protobuf.PersonOuterClass.Person.Builder.class);
			}

			// Construct using
			// com.xyz.protobuf.PersonOuterClass.Person.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.xyz.protobuf.PersonOuterClass.internal_static_com_xyz_protobuf_Person_descriptor;
			}

			public com.xyz.protobuf.PersonOuterClass.Person getDefaultInstanceForType() {
				return com.xyz.protobuf.PersonOuterClass.Person.getDefaultInstance();
			}

			public com.xyz.protobuf.PersonOuterClass.Person build() {
				com.xyz.protobuf.PersonOuterClass.Person result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.xyz.protobuf.PersonOuterClass.Person buildPartial() {
				com.xyz.protobuf.PersonOuterClass.Person result = new com.xyz.protobuf.PersonOuterClass.Person(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.xyz.protobuf.PersonOuterClass.Person) {
					return mergeFrom((com.xyz.protobuf.PersonOuterClass.Person) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.xyz.protobuf.PersonOuterClass.Person other) {
				if (other == com.xyz.protobuf.PersonOuterClass.Person.getDefaultInstance())
					return this;
				if (other.hasId()) {
					bitField0_ |= 0x00000001;
					id_ = other.id_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.xyz.protobuf.PersonOuterClass.Person parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.xyz.protobuf.PersonOuterClass.Person) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object id_ = "";

			/**
			 * <code>required string id = 1;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string id = 1;</code>
			 */
			public java.lang.String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						id_ = s;
					}
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string id = 1;</code>
			 */
			public com.google.protobuf.ByteString getIdBytes() {
				java.lang.Object ref = id_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					id_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string id = 1;</code>
			 */
			public Builder setId(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string id = 1;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			/**
			 * <code>required string id = 1;</code>
			 */
			public Builder setIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.xyz.protobuf.Person)
		}

		static {
			defaultInstance = new Person(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.xyz.protobuf.Person)
	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_com_xyz_protobuf_Person_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_xyz_protobuf_Person_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

	static {
		java.lang.String[] descriptorData = {
				"\n\014person.proto\022\020com.xyz.protobuf\"\024\n\006Pers" + "on\022\n\n\002id\030\001 \002(\t" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_com_xyz_protobuf_Person_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_com_xyz_protobuf_Person_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
				internal_static_com_xyz_protobuf_Person_descriptor, new java.lang.String[] { "Id", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
